/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reporte1;

/**
 *
 * @author deleo
 */
public class General1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(General1.class.getName());

    /**
     * Creates new form General1
     */
    public General1() {
        initComponents();
        this.setLocationRelativeTo(null); 
        configurarTabla();               
        cargarDatosDesdeBaseDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Reporte General del condominio");

        jButton1.setText("Refresh");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Casa", "Propietario", "Estado del Mes actual (pagado/Pendiente)", "Total pagado al año Actual"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Total Recaudado: Q[Suma de los pagados] / Total Esperado: Q45000.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
cargarDatosDesdeBaseDatos();        // TODO add your handling code here:
    }                                        
private void configurarTabla() {
        jTable1.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (table.getValueAt(row, 2) != null) {
                    String estado = table.getValueAt(row, 2).toString();
                    if (column == 2) {
                        if ("Pagado".equalsIgnoreCase(estado)) {
                            c.setForeground(new java.awt.Color(0, 153, 0)); // Verde
                        } else {
                            c.setForeground(java.awt.Color.RED); // Rojo
                        }
                    } else {
                        c.setForeground(java.awt.Color.BLACK); // El resto negro
                    }
                }
                return c;
            }
        });
    }
    private java.sql.Connection conectar() {
        try {
            String url = "jdbc:sqlite:condominio_vistaverde.db"; 
            java.sql.Connection conn = java.sql.DriverManager.getConnection(url);
            
            // Crea de forma automática la tabla si no existe al iniciar
            if (conn != null) {
                String crearTablaSql = "CREATE TABLE IF NOT EXISTS Casas ("
                        + " numero_casa INTEGER PRIMARY KEY,"
                        + " nombre_encargado TEXT NOT NULL,"
                        + " estado_pago TEXT NOT NULL,"
                        + " telefono TEXT,"
                        + " correo TEXT"
                        + ");";
                try (java.sql.Statement stmt = conn.createStatement()) {
                    stmt.execute(crearTablaSql);
                }
            }
            return conn;
        } catch (java.sql.SQLException e) {
            System.out.println("Error de conexión: " + e.getMessage());
            return null;
        }
    }

           private void cargarDatosDesdeBaseDatos() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 
        
        double totalRecaudado = 0;
        double cuotaBase = 1500.00; // CRITERIO 1: Ajuste automático de cuota
        double totalEsperado = cuotaBase * 30; // FÓRMULA 1: Total Esperado

        // 1. LLENADO AUTOMÁTICO: Insertamos las 30 casas si la base de datos está limpia
        try (java.sql.Connection conn = conectar();
             java.sql.Statement stmt = conn.createStatement()) {
            
            java.sql.ResultSet rsCheck = stmt.executeQuery("SELECT COUNT(*) FROM Casas");
            if (rsCheck.next() && rsCheck.getInt(1) == 0) {
                for (int i = 1; i <= 30; i++) {
                    String estado = (i % 4 == 0) ? "Pendiente" : "Pagado";
                    String query = String.format(
                        "INSERT INTO Casas (numero_casa, nombre_encargado, estado_pago, telefono) VALUES (%d, 'Propietario Casa %d', '%s', '4412-000%d')",
                        i, i, estado, i
                    );
                    stmt.executeUpdate(query);
                }
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Aviso de inicialización: " + e.getMessage());
        }

        // 2. CONSULTA Y RENDERIZADO DE REQUERIMIENTOS JIRA
        String sql = "SELECT numero_casa, nombre_encargado, estado_pago FROM Casas";

        try (java.sql.Connection conn = conectar();
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(sql)) {
             
            while (rs.next()) {
                int numCasa = rs.getInt("numero_casa");
                String propietario = rs.getString("nombre_encargado");
                String estado = rs.getString("estado_pago");
                
                // FÓRMULA 2: Suma de pagos registrados
                double pagadoAlMes = "Pagado".equalsIgnoreCase(estado) ? cuotaBase : 0;
                if ("Pagado".equalsIgnoreCase(estado)) {
                    totalRecaudado += cuotaBase;
                }

                // CRITERIO 2: Formato de moneda guatemalteca (Q) con comas
                modelo.addRow(new Object[]{
                    numCasa, 
                    propietario, 
                    estado, 
                    String.format("Q%,.2f", pagadoAlMes)
                });
            }
            
            // FÓRMULA 3: Porcentaje de recaudación
            double porcentajeRecaudacion = (totalEsperado > 0) ? (totalRecaudado / totalEsperado) * 100 : 0;
            
            // CRITERIO 2: Banner inferior formateado
            jLabel2.setText(String.format(
                "Total Recaudado: Q%,.2f / Total Esperado: Q%,.2f / Porcentaje de recaudación: %.1f%%", 
                totalRecaudado, totalEsperado, porcentajeRecaudacion
            ));
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar la BD: " + e.getMessage());
        }
    }



    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
    


