/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registropropietario;

/**
 * Clase ConfiguraciónCuotas.
 *
 * Esta ventana permite administrar la cuota mensual
 * del condominio dentro del sistema de gestión residencial.
 *
 * Funciones principales:
 * - Consultar la cuota vigente almacenada en la base de datos.
 * - Actualizar el monto de la cuota mensual.
 * - Validar que los valores ingresados sean correctos.
 * - Guardar los cambios en la base de datos.
 * - Notificar por correo electrónico a los propietarios
 *   registrados sobre la actualización realizada.
 *
 * La cuota configurada se utiliza para los pagos futuros
 * de mantenimiento del residencial.
 *
 * @author Gerardo Silvestre
 * @version 1.0
 * @since 2026
 */
public class ConfiguraciónCuotas extends javax.swing.JFrame {
    
  /**
 * Almacena la cuota vigente del condominio.
 *
 * Se declara como estática para que su valor
 * pueda ser utilizado desde cualquier parte
 * del sistema durante la ejecución del programa.
 */
 // Variable estática para mantener la cuota vigente durante toda la sesión
public static double cuotaVigente = 1500.00;
    

    /**
 * Constructor de la ventana ConfiguraciónCuotas.
 *
 * Inicializa los componentes gráficos,
 * configura la ventana y carga la cuota
 * actual almacenada en la base de datos.
 */
    public ConfiguraciónCuotas() {
        initComponents();
        configurarVentana();
        cargarCuotaActual();
    }
    
    /**
 * Configura propiedades generales de la ventana.
 *
 * - Centra la ventana en la pantalla.
 * - Evita que el usuario modifique su tamaño.
 */
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
 * Obtiene la cuota vigente desde la base de datos.
 *
 * Consulta la tabla Configuracion para recuperar
 * el valor actual de la cuota mensual y mostrarlo
 * en la interfaz gráfica.
 *
 * En caso de error se muestra un mensaje informativo.
 */
    private void cargarCuotaActual() {
        // TODO: BD — cuando tengas tabla de configuración, leer de ahí
        // Por ahora muestra el valor fijo
        String sql = "SELECT cuota FROM Configuracion WHERE id = 1";
    try (java.sql.Connection con = ConexionDB.getConexion();
         java.sql.Statement st = con.createStatement();
         java.sql.ResultSet rs = st.executeQuery(sql)) {
        if (rs.next()) {
            cuotaVigente = rs.getDouble("cuota");
            jLabel2.setText("Q. " + String.format("%,.2f", cuotaVigente));
        }
    } catch (java.sql.SQLException e) {
        mostrarError("Error al cargar cuota: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cuota Actual");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Q. 1,500.00");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nueva cuota");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Configuración de Cuotas");

        jButton2.setBackground(new java.awt.Color(255, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
 * Evento ejecutado al presionar el botón "Actualizar".
 *
 * Realiza las siguientes acciones:
 *
 * 1. Valida que el campo no esté vacío.
 * 2. Verifica que el valor ingresado sea numérico.
 * 3. Comprueba que la cuota sea mayor a cero.
 * 4. Solicita confirmación al administrador.
 * 5. Actualiza el valor en la base de datos.
 * 6. Actualiza la cuota vigente en memoria.
 * 7. Envía correos de notificación a los propietarios.
 * 8. Muestra un resumen del proceso realizado.
 *
 * @param evt Evento generado por el botón.
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nuevaCuotaStr = jTextField1.getText().trim();

        // 1. Validar que no esté vacío
        if (nuevaCuotaStr.isEmpty()) {
            mostrarError("Ingresa el monto de la nueva cuota.");
            jTextField1.requestFocus();
            return;
        }

        // 2. Validar que sea número válido
        double nuevaCuota;
        try {
            nuevaCuota = Double.parseDouble(nuevaCuotaStr.replace(",", "."));
        } catch (NumberFormatException e) {
            mostrarError("El monto ingresado no es un número válido.\nEjemplo: 1500 o 1500.00");
            jTextField1.requestFocus();
            return;
        }

        // 3. Validar que sea positivo
        if (nuevaCuota <= 0) {
            mostrarError("El monto de la cuota debe ser mayor a cero.");
            jTextField1.requestFocus();
            return;
        }

        // 4. Confirmar el cambio
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de cambiar la cuota a Q. " + String.format("%,.2f", nuevaCuota) + "?\n"
              + "Este cambio solo aplicará a pagos futuros.",
                "Confirmar cambio",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        // 5. Guardar en BD
        // TODO: BD — cuando tengas tabla Configuracion, usar:
        // UPDATE Configuracion SET cuota = ? WHERE id = 1
        // Por ahora solo actualizamos el label
        String sqlUpdate = "UPDATE Configuracion SET cuota = ? WHERE id = 1";
try (java.sql.Connection con = ConexionDB.getConexion();
     java.sql.PreparedStatement ps = con.prepareStatement(sqlUpdate)) {
    ps.setDouble(1, nuevaCuota);
    ps.executeUpdate();
    cuotaVigente = nuevaCuota;
    jLabel2.setText("Q. " + String.format("%,.2f", cuotaVigente));
} catch (java.sql.SQLException e) {
    mostrarError("Error al guardar cuota: " + e.getMessage());
    return;
}
        // 6. Notificar por correo a todos los propietarios con correo registrado
        int enviados = 0;
        int fallidos = 0;
        String asunto = "Actualización de cuota mensual";
        String sqlPropietarios = "SELECT nombre, correo FROM Propietarios "
                               + "WHERE correo IS NOT NULL AND correo <> ''";
        try (java.sql.Connection con = ConexionDB.getConexion();
             java.sql.PreparedStatement ps = con.prepareStatement(sqlPropietarios);
             java.sql.ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                String nombre = rs.getString("nombre");
                String correo = rs.getString("correo");
                String cuerpo = "Estimado(a) " + nombre + ",\n\n"
                              + "Le informamos que la cuota mensual ha sido actualizada:\n\n"
                              + "  Nueva cuota: Q. " + String.format("%,.2f", nuevaCuota) + "\n\n"
                              + "Este cambio aplica solo a pagos futuros.\n\n"
                              + "Atentamente,\n" + EmailConfig.NOMBRE_REMITENTE;
                try {
                    EnviarCorreo.enviar(correo, asunto, cuerpo);
                    enviados++;
                } catch (javax.mail.MessagingException me) {
                    fallidos++;
                }
            }
        } catch (java.sql.SQLException e) {
            mostrarError("La cuota se actualizó, pero falló la consulta de "
                       + "propietarios para notificar: " + e.getMessage());
            jTextField1.setText("");
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this,
                "Cuota actualizada exitosamente.\n"
              + "Nueva cuota: Q. " + String.format("%,.2f", nuevaCuota) + "\n"
              + "El cambio aplica solo a pagos futuros.\n\n"
              + "Correos enviados: " + enviados + "\n"
              + "Correos fallidos: " + fallidos,
                "Actualización exitosa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        jTextField1.setText("");
    }

    /**
 * Muestra un mensaje de advertencia al usuario.
 *
 * Se utiliza para informar errores de validación
 * o situaciones que impiden continuar con una operación.
 *
 * @param mensaje Texto que será mostrado al usuario.
 */
    private void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
 * Evento ejecutado al presionar el botón "Volver".
 *
 * Regresa al menú principal del sistema y
 * cierra la ventana actual.
 *
 * @param evt Evento generado por el botón.
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MenuInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
 * Método principal de ejecución.
 *
 * Inicializa la interfaz gráfica utilizando
 * el tema Nimbus y muestra la ventana de
 * configuración de cuotas.
 *
 * @param args Argumentos enviados desde la línea
 *             de comandos.
 */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConfiguraciónCuotas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
