/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registropropietario;

/**
 *
 * @author silve
 */
public class ConfiguraciónCuotas extends javax.swing.JFrame {
    
    // Variable estática para mantener la cuota vigente durante toda la sesión
public static double cuotaVigente = 1500.00;
    

    /**
     * Creates new form ConfiguraciónCuotas
     */
    public ConfiguraciónCuotas() {
        initComponents();
        configurarVentana();
        cargarCuotaActual();
    }
    
    
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void cargarCuotaActual() {
        // TODO: BD — cuando tengas tabla de configuración, leer de ahí
        // Por ahora muestra el valor fijo
        String sql = "SELECT cuota FROM Configuracion WHERE id = 1";
    try (java.sql.Connection con = ConexionDB.getConexion();
         java.sql.Statement st = con.createStatement();
         java.sql.ResultSet rs = st.executeQuery(sql)) {
        if (rs.next()) {
            cuotaVigente = rs.getDouble("cuota");
            jLabel2.setText("Q. " + String.format("%,.2f", cuotaVigente));
        }
    } catch (java.sql.SQLException e) {
        mostrarError("Error al cargar cuota: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cuota Actual");

        jLabel2.setText("Q. 1,500.00");

        jLabel3.setText("Nueva cuota");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Volver");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel4.setText("Configuración de Cuotas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(150, 150, 150)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MenuInicio().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nuevaCuotaStr = jTextField1.getText().trim();

        // 1. Validar que no esté vacío
        if (nuevaCuotaStr.isEmpty()) {
            mostrarError("Ingresa el monto de la nueva cuota.");
            jTextField1.requestFocus();
            return;
        }

        // 2. Validar que sea número válido
        double nuevaCuota;
        try {
            nuevaCuota = Double.parseDouble(nuevaCuotaStr.replace(",", "."));
        } catch (NumberFormatException e) {
            mostrarError("El monto ingresado no es un número válido.\nEjemplo: 1500 o 1500.00");
            jTextField1.requestFocus();
            return;
        }

        // 3. Validar que sea positivo
        if (nuevaCuota <= 0) {
            mostrarError("El monto de la cuota debe ser mayor a cero.");
            jTextField1.requestFocus();
            return;
        }

        // 4. Confirmar el cambio
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de cambiar la cuota a Q. " + String.format("%,.2f", nuevaCuota) + "?\n"
              + "Este cambio solo aplicará a pagos futuros.",
                "Confirmar cambio",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        // 5. Guardar en BD
        // TODO: BD — cuando tengas tabla Configuracion, usar:
        // UPDATE Configuracion SET cuota = ? WHERE id = 1
        // Por ahora solo actualizamos el label
        String sqlUpdate = "UPDATE Configuracion SET cuota = ? WHERE id = 1";
try (java.sql.Connection con = ConexionDB.getConexion();
     java.sql.PreparedStatement ps = con.prepareStatement(sqlUpdate)) {
    ps.setDouble(1, nuevaCuota);
    ps.executeUpdate();
    cuotaVigente = nuevaCuota;
    jLabel2.setText("Q. " + String.format("%,.2f", cuotaVigente));
} catch (java.sql.SQLException e) {
    mostrarError("Error al guardar cuota: " + e.getMessage());
    return;
}
        javax.swing.JOptionPane.showMessageDialog(this,
                "Cuota actualizada exitosamente.\n"
              + "Nueva cuota: Q. " + String.format("%,.2f", nuevaCuota) + "\n"
              + "El cambio aplica solo a pagos futuros.",
                "Actualización exitosa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        jTextField1.setText("");
    }

    private void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConfiguraciónCuotas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
