/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registropropietario;

/**
 *
 * @author silve
 */
public class Estadodecuenta extends javax.swing.JFrame {
    
    public Estadodecuenta() {
    initComponents();
    configurarVentana();
    cargarCasas();
    jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
}

private void configurarVentana() {
    setLocationRelativeTo(null);
    setResizable(false);
}

private void cargarCasas() {
    jComboBox1.removeAllItems();
    jComboBox1.addItem("Seleccione una casa");
    for (int i = 1; i <= 30; i++) {
        jComboBox1.addItem(String.valueOf(i));
    }
}

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
    String seleccion = (String) jComboBox1.getSelectedItem();
    if (seleccion == null || seleccion.equals("Seleccione una casa")) {
        jLabel3.setText("Selecciona una casa para ver la información.");
        limpiarTabla();
        return;
    }
    int numeroCasa = Integer.parseInt(seleccion);
    cargarDatosCasa(numeroCasa);
}

private void cargarDatosCasa(int numeroCasa) {
    // Consultar propietario
    String sqlPropietario = 
        "SELECT p.nombre, p.telefono, p.correo " +
        "FROM Casas c LEFT JOIN Propietarios p ON c.id_propietario = p.id_propietario " +
        "WHERE c.numero_casa = ?";

    try (java.sql.Connection con = ConexionDB.getConexion();
         java.sql.PreparedStatement ps = con.prepareStatement(sqlPropietario)) {
        ps.setInt(1, numeroCasa);
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next() && rs.getString("nombre") != null) {
            jLabel3.setText("<html>Nombre: " + rs.getString("nombre") +
                    "<br>Teléfono: " + rs.getString("telefono") +
                    "<br>Correo: " + rs.getString("correo") + "</html>");
        } else {
            jLabel3.setText("Esta casa no tiene propietario registrado.");
            limpiarTabla();
            return;
        }
    } catch (java.sql.SQLException e) {
        jLabel3.setText("Error al cargar propietario.");
        return;
    }

    // Consultar pagos
    String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio",
                      "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};

    javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);

    double totalPagado = 0;
    double totalPendiente = 0;

    String sqlCuota = "SELECT cuota FROM Configuracion WHERE id = 1";
    double cuota = 1500.00;
    try (java.sql.Connection con = ConexionDB.getConexion();
         java.sql.Statement st = con.createStatement();
         java.sql.ResultSet rs = st.executeQuery(sqlCuota)) {
        if (rs.next()) cuota = rs.getDouble("cuota");
    } catch (java.sql.SQLException e) { }

    for (int i = 0; i < 12; i++) {
        String sqlPago = "SELECT COUNT(*) FROM Pagos WHERE numero_casa = ? AND mes = ?";
        try (java.sql.Connection con = ConexionDB.getConexion();
             java.sql.PreparedStatement ps = con.prepareStatement(sqlPago)) {
            ps.setInt(1, numeroCasa);
            ps.setInt(2, i + 1);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                modelo.addRow(new Object[]{meses[i], "✅ Pagado"});
                totalPagado += cuota;
            } else {
                modelo.addRow(new Object[]{meses[i], "❌ Pendiente"});
                totalPendiente += cuota;
            }
        } catch (java.sql.SQLException e) {
            modelo.addRow(new Object[]{meses[i], "Error"});
        }
    }

    jLabel5.setText("Total Pagado: Q " + String.format("%,.2f", totalPagado));
    jLabel6.setText("Total Pendiente: Q " + String.format("%,.2f", totalPendiente));
}

private void limpiarTabla() {
    javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);
    jLabel5.setText("Total Pagado: Q 0.00");
    jLabel6.setText("Total Pendiente: Q 0.00");
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estado de cuentas");

        jLabel2.setText("Seleccionar casa:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mes", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Detalle de pagos mensuales");

        jButton1.setText("Volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel5.setBackground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Total pagado del año:");

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Total pendiente del año:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenuInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        com.formdev.flatlaf.FlatLightLaf.setup();
    } catch (Exception e) { }
    java.awt.EventQueue.invokeLater(() -> new Estadodecuenta().setVisible(true));

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Estadodecuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
