/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registropropietario;

/**
 * Ventana de Reporte General del Condominio.
 * Muestra las 30 casas con su propietario, estado de pago del mes actual
 * y el total pagado en el año. Al pie se muestra el resumen de recaudación.
 *
 * @author deleo
 */
public class General extends javax.swing.JFrame {

    // Logger para registrar eventos o errores en la consola
    private static final java.util.logging.Logger registrador =
            java.util.logging.Logger.getLogger(General.class.getName());

    /**
     * Constructor: inicializa los componentes gráficos,
     * centra la ventana, configura la tabla y carga los datos.
     */
    public General() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en pantalla
        configurarTabla();                // Aplica colores a la columna de estado
        cargarDatosDesdeBaseDatos();      // Llena la tabla con datos reales
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reporte General del Condominio");

        jButton1.setText("Volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Refresh");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Casa", "Propietario", "Estado del mes actual", "Total pagado en el año"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Total Recaudado: Q(Suma de los pagados)/ Total Esperado: Q45,000.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción del botón "Refresh": recarga los datos desde la base de datos.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarDatosDesdeBaseDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Acción del botón "Volver": regresa al menú principal.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // CONFIGURACIÓN VISUAL DE LA TABLA
    

    /**
     * Aplica un renderizador personalizado a la tabla para colorear
     * la columna "Estado": verde si está Pagado, rojo si está Pendiente.
     * Las demás columnas se muestran en negro normal.
     */
    private void configurarTabla() {
        jTable1.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable tabla, Object valor,
                    boolean estaSeleccionado, boolean tieneFoco, int fila, int columna) {

                // Llamamos al renderizador base para mantener el estilo por defecto
                java.awt.Component celda = super.getTableCellRendererComponent(
                        tabla, valor, estaSeleccionado, tieneFoco, fila, columna);

                // Solo cambiamos color si la fila NO está seleccionada
                // (para no tapar el azul de selección)
                if (!estaSeleccionado) {
                    Object estadoObj = tabla.getModel().getValueAt(fila, 2);
                    if (estadoObj != null) {
                        String estado = estadoObj.toString();

                        if (columna == 2) {
                            // Columna de estado: verde = Pagado, rojo = Pendiente
                            if ("Pagado".equalsIgnoreCase(estado)) {
                                celda.setForeground(new java.awt.Color(0, 153, 0));
                            } else {
                                celda.setForeground(java.awt.Color.RED);
                            }
                        } else {
                            // Resto de columnas siempre en negro
                            celda.setForeground(java.awt.Color.BLACK);
                        }
                    }
                }
                return celda;
            }
        });
    }

    
    // CONEXIÓN A LA BASE DE DATOS
    

    /**
     * Abre y devuelve una conexión SQLite a la base de datos del condominio.
     * El archivo .db debe estar en la carpeta raíz del proyecto (junto a /src).
     *
     * @return Conexión activa, o null si falla.
     */
    private java.sql.Connection conectar() {
        try {
            // Registramos el driver de SQLite explícitamente
            Class.forName("org.sqlite.JDBC");

            // Ruta relativa: el archivo debe estar en la raíz del proyecto NetBeans
            String urlConexion = "jdbc:sqlite:BD/condominio_vistaverde.db";
            return java.sql.DriverManager.getConnection(urlConexion);

        } catch (ClassNotFoundException e) {
            // El driver SQLite no está en el classpath del proyecto
            javax.swing.JOptionPane.showMessageDialog(this,
                "Driver SQLite no encontrado.\n"
                + "Agrega la librería sqlite-jdbc al proyecto en:\n"
                + "Propiedades del Proyecto → Librerías → Agregar JAR",
                "Error de driver", javax.swing.JOptionPane.ERROR_MESSAGE);
            return null;

        } catch (java.sql.SQLException e) {
            // No se pudo abrir el archivo de base de datos
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se pudo conectar a la base de datos:\n" + e.getMessage(),
                "Error de conexión", javax.swing.JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    
    // CARGA DE DATOS PRINCIPAL
    

    /**
     * Consulta la base de datos y llena la tabla con:
     *  - Número de casa
     *  - Nombre del propietario (o "Sin propietario" si no tiene asignado)
     *  - Estado del mes actual (Pagado / Pendiente)
     *  - Total pagado en el año actual (suma de todos sus pagos del año)
     *
     * Al finalizar, actualiza el pie del reporte con el resumen de recaudación.
     */
    private void cargarDatosDesdeBaseDatos() {

        // Limpiamos la tabla antes de volver a llenarla
        javax.swing.table.DefaultTableModel modeloTabla =
                (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modeloTabla.setRowCount(0);

        // Obtenemos el mes y año actuales para evaluar el estado del mes en curso
        java.time.LocalDate hoy = java.time.LocalDate.now();
        int mesActual  = hoy.getMonthValue(); // 1 = enero ... 12 = diciembre
        int añoActual  = hoy.getYear();

        // Abrimos la conexión; si falla, salimos sin hacer nada más
        java.sql.Connection conexion = conectar();
        if (conexion == null) return;

        try {
            // -----------------------------------------------------------------
            // PASO 1: Leer la cuota vigente desde la tabla Configuracion
            // -----------------------------------------------------------------
            double cuotaVigente = 1500.0; // Valor por defecto si la tabla está vacía

            try (java.sql.Statement stmtCuota = conexion.createStatement();
                 java.sql.ResultSet rsCuota = stmtCuota.executeQuery(
                         "SELECT cuota FROM Configuracion LIMIT 1")) {

                if (rsCuota.next()) {
                    cuotaVigente = rsCuota.getDouble(1);
                }
            }

            // Total esperado = cuota × 30 casas
            double totalEsperado  = cuotaVigente * 30;
            double totalRecaudado = 0; // Se acumulará por cada casa

            // -----------------------------------------------------------------
            // PASO 2: Consulta principal con JOINs
            //
            // Une las tablas:
            //   Casas  →  Propietarios  (para el nombre del encargado)
            //   Casas  →  Pagos del mes actual  (para saber si pagó este mes)
            //   Casas  →  Suma de pagos del año (para la columna "Total Año")
            // -----------------------------------------------------------------
            String consultaSql =
                "SELECT " +
                "  c.numero_casa, " +
                // Si no tiene propietario asignado, muestra texto amigable
                "  COALESCE(p.nombre, 'Sin propietario') AS nombre_propietario, " +
                // Si existe un pago en el mes y año actuales → Pagado, si no → Pendiente
                "  CASE WHEN pago_mes.id_pago IS NOT NULL THEN 'Pagado' ELSE 'Pendiente' END AS estado_mes, " +
                // Suma de todos los pagos del año; si no hay pagos devuelve 0
                "  COALESCE(resumen_año.total_año, 0) AS total_pagado_año " +
                "FROM Casas c " +
                // JOIN para obtener el nombre del propietario
                "LEFT JOIN Propietarios p " +
                "  ON c.id_propietario = p.id_propietario " +
                // JOIN para verificar si pagó en el mes actual
                "LEFT JOIN Pagos pago_mes " +
                "  ON pago_mes.numero_casa = c.numero_casa " +
                "  AND pago_mes.mes = ? " +   // parámetro: mes actual
                "  AND pago_mes.año = ? " +   // parámetro: año actual
                // Subconsulta: suma de pagos por casa en el año actual
                "LEFT JOIN ( " +
                "  SELECT numero_casa, SUM(monto) AS total_año " +
                "  FROM Pagos " +
                "  WHERE año = ? " +          // parámetro: año actual
                "  GROUP BY numero_casa " +
                ") resumen_año ON resumen_año.numero_casa = c.numero_casa " +
                "ORDER BY c.numero_casa";     // Ordenamos por número de casa

            try (java.sql.PreparedStatement sentencia = conexion.prepareStatement(consultaSql)) {

                // Asignamos los tres parámetros de la consulta
                sentencia.setInt(1, mesActual);
                sentencia.setInt(2, añoActual);
                sentencia.setInt(3, añoActual);

                try (java.sql.ResultSet resultado = sentencia.executeQuery()) {

                    // Recorremos cada una de las 30 casas
                    while (resultado.next()) {
                        int    numeroCasa    = resultado.getInt("numero_casa");
                        String propietario   = resultado.getString("nombre_propietario");
                        String estadoMes     = resultado.getString("estado_mes");
                        double totalPagadoAño = resultado.getDouble("total_pagado_año");

                        // Acumulamos para el pie del reporte
                        totalRecaudado += totalPagadoAño;

                        // Agregamos la fila a la tabla con formato de moneda guatemalteca
                        modeloTabla.addRow(new Object[]{
                            numeroCasa,
                            propietario,
                            estadoMes,
                            String.format("Q%,.2f", totalPagadoAño)
                        });
                    }
                }
            }

            // -----------------------------------------------------------------
            // PASO 3: Actualizar el pie del reporte con el resumen financiero
            // -----------------------------------------------------------------
            double porcentajeRecaudacion = (totalEsperado > 0)
                    ? (totalRecaudado / totalEsperado) * 100
                    : 0;

            jLabel2.setText(String.format(
                "Total Recaudado: Q%,.2f  /  Total Esperado: Q%,.2f  /  Recaudación: %.1f%%",
                totalRecaudado, totalEsperado, porcentajeRecaudacion));

        } catch (java.sql.SQLException e) {
            // Mostramos el error al usuario si algo falla durante la consulta
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al cargar los datos:\n" + e.getMessage(),
                "Error de consulta", javax.swing.JOptionPane.ERROR_MESSAGE);

        } finally {
            // Siempre cerramos la conexión al terminar, haya error o no
            try { conexion.close(); } catch (java.sql.SQLException ignorar) {}
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
