/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registropropietario;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;

/**
 * /**
 * Clase Login.
 *
 * Esta ventana permite al usuario iniciar sesión dentro del sistema
 * de Registro de Propietarios de Residencial Vista Verde.
 *
 * Funciones principales:
 * - Solicitar usuario y contraseña.
 * - Validar credenciales.
 * - Mostrar mensajes de error si los datos son incorrectos.
 * - Redirigir al menú principal cuando el acceso es exitoso.
 *
 *
 * @author silve
 */
public class Login extends javax.swing.JFrame {
    
    /**
     * Usuario autorizado para acceder al sistema.
     */
    private static final String USUARIO = "iusr_vistaverde";
    
     /**
     * Contraseña autorizada para acceder al sistema.
     */
    private static final String PASSWORD = "R3sidencial2026%";

    /**
     * Constructor de la ventana Login.
     *
     * Inicializa todos los componentes gráficos,
     * configura la ventana y carga el icono del sistema.
     */
    public Login() {
    initComponents();
    configurarVentana();
    jPasswordField1.setText("");
    addPlaceholder(jTextField1, "Ingrese su usuario");
    
    java.net.URL imgURL = getClass().getResource("/images/Icono.png");
    if (imgURL != null) {
        java.awt.Image img = new javax.swing.ImageIcon(imgURL).getImage();
        java.awt.Image imgRedimensionada = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
        jLabel4.setIcon(new javax.swing.ImageIcon(imgRedimensionada));
    } else {
        System.out.println("Imagen no encontrada");
    }
}
    
    /**
     * Configura propiedades generales de la ventana.
     *
     * - Centra la ventana en pantalla.
     * - Impide que el usuario cambie su tamaño.
     */
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    /**
     * Agrega un texto de ayuda (placeholder) a un campo de texto.
     *
     * Cuando el usuario hace clic en el campo, el texto desaparece.
     * Si el usuario abandona el campo vacío, el texto vuelve a mostrarse.
     *
     * @param field Campo de texto donde se colocará el placeholder.
     * @param placeholder Texto informativo que se mostrará.
     */
    private void addPlaceholder(JTextField field, String placeholder) {
    field.setText(placeholder);
    field.setForeground(Color.GRAY);
    field.addFocusListener(new FocusAdapter() {
        
        /**
        * Se ejecuta cuando el usuario selecciona el campo.
        */
        @Override
        public void focusGained(FocusEvent e) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(field.getParent().getForeground()); // color del tema
            }
            
        /**
        * Se ejecuta cuando el usuario abandona el campo.
        */
        }
        @Override
        public void focusLost(FocusEvent e) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(Color.GRAY);
            }
        }
    });
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Inicio de sesión");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Iniciar sesión");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jPasswordField1.setText("jPasswordField1");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icono.png"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(256, 256));
        jLabel4.setPreferredSize(new java.awt.Dimension(256, 256));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 /**
 * Evento ejecutado al presionar el botón "Iniciar sesión".
 *
 * Realiza las siguientes acciones:
 * 1. Obtiene el usuario y contraseña ingresados.
 * 2. Verifica que los campos no estén vacíos.
 * 3. Compara los datos con las credenciales registradas.
 * 4. Permite el acceso al sistema si son correctos.
 * 5. Muestra mensajes de error si son incorrectos.
 *
 * @param evt Evento generado por el botón.
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usuario = jTextField1.getText().trim();
    String password = new String(jPasswordField1.getPassword());

    if (usuario.isEmpty() || usuario.equals("Ingrese su usuario") || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor ingresa usuario y contraseña.",
                "Campos vacíos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (usuario.equals(USUARIO) && password.equals(PASSWORD)) {
        new MenuInicio().setVisible(true);
        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Usuario o contraseña incorrectos.\nIntenta de nuevo.",
                "Error de autenticación",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        jPasswordField1.setText("");
        jPasswordField1.requestFocus();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

 /**
 * Evento ejecutado al presionar el botón "Cerrar".
 *
 * Finaliza completamente la ejecución del programa.
 *
 * @param evt Evento generado por el botón.
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
 * Método principal del programa.
 *
 * Punto de entrada de la aplicación.
 * Inicializa el tema gráfico FlatLaf Dark
 * y muestra la ventana de inicio de sesión.
 *
 * @param args Argumentos enviados desde la línea de comandos.
 */
        public static void main(String args[]) {
    try {
        com.formdev.flatlaf.FlatDarculaLaf.setup();
    } catch (Exception e) {
        // ignorar
    }
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
