/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registropropietario;

/**
 * Ventana encargada del registro de pagos mensuales del condominio.
 *
 * Permite seleccionar una casa, el mes y el año del pago para
 * registrar la cuota correspondiente en la base de datos.
 *
 * Antes de registrar un pago, el sistema realiza diversas
 * validaciones para garantizar la integridad de la información:
 *
 * - Verifica que la casa tenga propietario registrado.
 * - Evita pagos duplicados.
 * - Controla que los meses se paguen en orden cronológico.
 * - Verifica que exista un correo electrónico registrado.
 * - Envía una confirmación automática por correo electrónico.
 *
 * Además, registra el monto vigente configurado en el sistema
 * para mantener un historial exacto de los pagos realizados.
 *
 * @author Gerardo Silvestre
 */
public class RPagos extends javax.swing.JFrame {
    
    
/**
 * Constructor de la ventana de registro de pagos.
 *
 * Inicializa los componentes gráficos,
 * configura la ventana y muestra
 * el valor actual de la cuota mensual.
 */
    public RPagos() {
        initComponents();
        configurarVentana();
        mostrarMonto();
        configurarComboBoxes();
    }
    
    /**
 * Agrega la opción de texto guía al inicio de cada selector,
 * para que el usuario sepa qué debe elegir antes de registrar.
 */
private void configurarComboBoxes() {

    // Número de casa: inserta el placeholder al inicio
    jComboBox1.insertItemAt("Seleccione una casa", 0);
    jComboBox1.setSelectedIndex(0);

    // Mes: inserta el placeholder al inicio
    jComboBox2.insertItemAt("Seleccione un mes", 0);
    jComboBox2.setSelectedIndex(0);

    // Año: inserta el placeholder al inicio
    jComboBox3.insertItemAt("Seleccione un año", 0);
    jComboBox3.setSelectedIndex(0);
}

    /**
 * Configura la apariencia básica de la ventana.
 *
 * - Centra la ventana en la pantalla.
 * - Impide que el usuario cambie su tamaño.
 */
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    /**
 * Obtiene desde la base de datos el valor actual
 * de la cuota mensual y lo muestra en pantalla.
 *
 * Si ocurre algún error durante la consulta,
 * se muestra el valor predeterminado de Q.1,500.00.
 */
    private void mostrarMonto() {
    String sql = "SELECT cuota FROM Configuracion WHERE id = 1";
    try (java.sql.Connection con = ConexionDB.getConexion();
         java.sql.Statement st = con.createStatement();
         java.sql.ResultSet rs = st.executeQuery(sql)) {
        if (rs.next()) {
            double cuota = rs.getDouble("cuota");
            jLabel6.setText("Q. " + String.format("%,.2f", cuota));
        }
    } catch (java.sql.SQLException e) {
        jLabel6.setText("Q. 1,500.00");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Pagos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Número de casa:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mes:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Año:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Monto:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Q. 1,500.00");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre ", "Diciembre" }));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2027" }));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Registrar Pago");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nota: El cambio solo aplicará para pagos futuros");

        jButton2.setBackground(new java.awt.Color(255, 51, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(82, 82, 82))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
 * Registra un nuevo pago mensual.
 *
 * El proceso incluye:
 *
 * 1. Validar que los datos estén completos.
 * 2. Verificar que la casa tenga propietario.
 * 3. Evitar pagos duplicados.
 * 4. Validar la secuencia de meses.
 * 5. Obtener el correo del propietario.
 * 6. Registrar el pago en la base de datos.
 * 7. Enviar una confirmación por correo.
 * 8. Confirmar la transacción.
 *
 * Si ocurre algún error, el pago no se guarda.
 *
 * @param evt evento generado al presionar el botón
 *            "Registrar Pago".
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String casaSel  = (String) jComboBox1.getSelectedItem();
        String mesSel   = (String) jComboBox2.getSelectedItem();
        String anioSel  = (String) jComboBox3.getSelectedItem();

        if (casaSel == null || mesSel == null || anioSel == null
                || casaSel.equals("Seleccione una casa")
                || mesSel.equals("Seleccione un mes")
                || anioSel.equals("Seleccione un año")) {
            mostrarError("Selecciona la casa, el mes y el año antes de registrar.");
            return;
        }

        int numeroCasa = Integer.parseInt(casaSel);
        int anio       = Integer.parseInt(anioSel);

        // Convertir mes a número
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio",
                          "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
        int numeroMes = java.util.Arrays.asList(meses).indexOf(mesSel.trim()) + 1;
        
         // Validar que la casa tenga propietario
        String sqlCasa = "SELECT id_propietario FROM Casas WHERE numero_casa = ?";
        try (java.sql.Connection con = ConexionDB.getConexion();
             java.sql.PreparedStatement ps = con.prepareStatement(sqlCasa)) {
            ps.setInt(1, numeroCasa);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next() && rs.getObject("id_propietario") == null) {
                mostrarError("La casa " + numeroCasa + " no tiene propietario registrado.\n"
                           + "No se puede registrar un pago para una casa deshabitada.");
                return;
            }
        } catch (java.sql.SQLException e) {
            mostrarError("Error al verificar la casa: " + e.getMessage());
            return;
        }

        // 1. Validar pago duplicado
        String sqlCheck = "SELECT COUNT(*) FROM Pagos WHERE numero_casa = ? AND mes = ? AND año = ?";
        try (java.sql.Connection con = ConexionDB.getConexion();
             java.sql.PreparedStatement ps = con.prepareStatement(sqlCheck)) {
            ps.setInt(1, numeroCasa);
            ps.setInt(2, numeroMes);
            ps.setInt(3, anio);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                mostrarError("La casa " + numeroCasa + " ya tiene registrado el pago de "
                        + mesSel + " " + anio + ".\nNo se permiten pagos duplicados.");
                return;
            }
        } catch (java.sql.SQLException e) {
            mostrarError("Error al verificar pago: " + e.getMessage());
            return;
        }

        // 2. Validar secuencia de meses
        if (!validarSecuenciaMeses(numeroCasa, numeroMes, anio, meses)) {
            return;
        }

        // 3. Obtener el propietario y su correo. Si no tiene correo registrado,
        //    no se registra el pago (el aviso es obligatorio).
        EnviarCorreo.Propietario prop = EnviarCorreo.propietarioPorCasa(numeroCasa);
        if (prop == null) {
            mostrarError("La casa " + numeroCasa + " no tiene un correo registrado.\n"
                       + "No se puede registrar el pago sin enviar la confirmación.");
            return;
        }

        // 4. Registrar el pago dentro de una transacción: solo se confirma si el
        //    correo se envía correctamente; si falla, se revierte.
        String sqlInsert = "INSERT INTO Pagos (numero_casa, mes, año, monto) VALUES (?, ?, ?, ?)";
        try (java.sql.Connection con = ConexionDB.getConexion()) {
            con.setAutoCommit(false);
            try (java.sql.PreparedStatement ps = con.prepareStatement(sqlInsert)) {
                ps.setInt(1, numeroCasa);
                ps.setInt(2, numeroMes);
                ps.setInt(3, anio);
                double cuotaActual = Double.parseDouble(jLabel6.getText().replace("Q. ", "").replace(",", ""));
                ps.setDouble(4, cuotaActual);
                ps.executeUpdate();

                String asunto = "Confirmación de pago - Casa " + numeroCasa;
                String cuerpo = "Estimado(a) " + prop.nombre + ",\n\n"
                              + "Se ha registrado exitosamente su pago:\n\n"
                              + "  Casa:   " + numeroCasa + "\n"
                              + "  Mes:    " + mesSel + " " + anio + "\n"
                              + "  Monto:  " + jLabel6.getText() + "\n\n"
                              + "Gracias por estar al día con sus cuotas.\n\n"
                              + "Atentamente,\n" + EmailConfig.NOMBRE_REMITENTE;

                try {
                    EnviarCorreo.enviar(prop.correo, asunto, cuerpo);
                } catch (javax.mail.MessagingException me) {
                    con.rollback();
                    mostrarError("El pago no se registró porque no se pudo enviar el "
                               + "correo de confirmación a " + prop.correo + ":\n"
                               + me.getMessage());
                    return;
                }

                con.commit();
            } catch (java.sql.SQLException e) {
                con.rollback();
                throw e;
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Pago registrado exitosamente.\n\n"
                  + "  Casa:   " + numeroCasa + "\n"
                  + "  Mes:    " + mesSel + " " + anio + "\n"
                  + "  Monto:  " + jLabel6.getText() + "\n\n"
                  + "Se envió la confirmación a " + prop.correo,
                    "Pago exitoso",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();

        } catch (java.sql.SQLException e) {
            mostrarError("Error al registrar pago: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
 * Regresa al menú principal del sistema.
 *
 * Cierra la ventana actual y abre
 * la ventana MenuInicio.
 *
 * @param evt evento generado al presionar
 *            el botón "Volver".
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MenuInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
 * Verifica que los pagos se registren
 * respetando el orden cronológico.
 *
 * Por ejemplo:
 * No se puede pagar marzo si febrero
 * aún no ha sido cancelado.
 *
 * @param numeroCasa casa a validar
 * @param mes mes seleccionado
 * @param anio año seleccionado
 * @param meses arreglo con nombres de meses
 *
 * @return true si la secuencia es válida,
 *         false en caso contrario.
 *  */
    private boolean validarSecuenciaMeses(int numeroCasa, int mes, int anio, String[] meses) {
        for (int i = 1; i < mes; i++) {
            String sqlCheck = "SELECT COUNT(*) FROM Pagos WHERE numero_casa = ? AND mes = ? AND año = ?";
            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.PreparedStatement ps = con.prepareStatement(sqlCheck)) {
                ps.setInt(1, numeroCasa);
                ps.setInt(2, i);
                ps.setInt(3, anio);
                java.sql.ResultSet rs = ps.executeQuery();
                if (rs.next() && rs.getInt(1) == 0) {
                    mostrarError("No se puede registrar el pago de " + meses[mes-1] + " " + anio + ".\n"
                               + "El mes de " + meses[i-1] + " " + anio + " está pendiente.");
                    return false;
                }
            } catch (java.sql.SQLException e) {
                mostrarError("Error al validar secuencia: " + e.getMessage());
                return false;
            }
        }
        return true;
    }

    /**
 * Restablece los controles del formulario
 * a sus valores iniciales después de registrar
 * un pago exitosamente.
 */
    private void limpiarFormulario() {
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
    }

    /**
 * Muestra un mensaje de advertencia
 * al usuario cuando ocurre un error
 * de validación.
 *
 * @param mensaje texto que será mostrado
 *                en la ventana emergente.
 */
    private void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    
    /**
 * Método principal de ejecución.
 *
 * Inicializa la interfaz gráfica
 * y muestra la ventana de registro
 * de pagos.
 *
 * @param args argumentos enviados
 *             desde la línea de comandos.
 */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RPagos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
