/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registropropietario;

/**
 *
 * @author silve
 */
public class RPagos extends javax.swing.JFrame {
    
    

    

    /**
     * Creates new form RPagos
     */
    public RPagos() {
        initComponents();
        configurarVentana();
        mostrarMonto();
    }

    private void configurarVentana() {
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    private void mostrarMonto() {
    String sql = "SELECT cuota FROM Configuracion WHERE id = 1";
    try (java.sql.Connection con = ConexionDB.getConexion();
         java.sql.Statement st = con.createStatement();
         java.sql.ResultSet rs = st.executeQuery(sql)) {
        if (rs.next()) {
            double cuota = rs.getDouble("cuota");
            jLabel6.setText("Q. " + String.format("%,.2f", cuota));
        }
    } catch (java.sql.SQLException e) {
        jLabel6.setText("Q. 1,500.00");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registro de Pagos");

        jLabel2.setText("Número de casa:");

        jLabel3.setText("Mes:");

        jLabel4.setText("Año:");

        jLabel5.setText("Monto:");

        jLabel6.setText("Q. 1,500.00");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una casa", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un año", "2026", "2027" }));

        jButton1.setText("Registrar Pago");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel7.setText("Nota: El cambio solo aplicará para pagos futuros");

        jButton2.setText("Volver");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String casaSel  = (String) jComboBox1.getSelectedItem();
        String mesSel   = (String) jComboBox2.getSelectedItem();
        String anioSel  = (String) jComboBox3.getSelectedItem();

        if (casaSel == null || mesSel == null || anioSel == null
                || casaSel.equals("Seleccione una casa")
                || mesSel.equals("Seleccione un mes")
                || anioSel.equals("Seleccione un año")) {
            mostrarError("Selecciona la casa, el mes y el año antes de registrar.");
            return;
        }

        int numeroCasa = Integer.parseInt(casaSel);
        int anio       = Integer.parseInt(anioSel);

        // Convertir mes a número
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio",
                          "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
        int numeroMes = java.util.Arrays.asList(meses).indexOf(mesSel.trim()) + 1;
        
         // Validar que la casa tenga propietario
        String sqlCasa = "SELECT id_propietario FROM Casas WHERE numero_casa = ?";
        try (java.sql.Connection con = ConexionDB.getConexion();
             java.sql.PreparedStatement ps = con.prepareStatement(sqlCasa)) {
            ps.setInt(1, numeroCasa);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next() && rs.getObject("id_propietario") == null) {
                mostrarError("La casa " + numeroCasa + " no tiene propietario registrado.\n"
                           + "No se puede registrar un pago para una casa deshabitada.");
                return;
            }
        } catch (java.sql.SQLException e) {
            mostrarError("Error al verificar la casa: " + e.getMessage());
            return;
        }

        // 1. Validar pago duplicado
        String sqlCheck = "SELECT COUNT(*) FROM Pagos WHERE numero_casa = ? AND mes = ? AND año = ?";
        try (java.sql.Connection con = ConexionDB.getConexion();
             java.sql.PreparedStatement ps = con.prepareStatement(sqlCheck)) {
            ps.setInt(1, numeroCasa);
            ps.setInt(2, numeroMes);
            ps.setInt(3, anio);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                mostrarError("La casa " + numeroCasa + " ya tiene registrado el pago de "
                        + mesSel + " " + anio + ".\nNo se permiten pagos duplicados.");
                return;
            }
        } catch (java.sql.SQLException e) {
            mostrarError("Error al verificar pago: " + e.getMessage());
            return;
        }

        // 2. Validar secuencia de meses
        if (!validarSecuenciaMeses(numeroCasa, numeroMes, anio, meses)) {
            return;
        }

        // 3. Obtener el propietario y su correo. Si no tiene correo registrado,
        //    no se registra el pago (el aviso es obligatorio).
        EnviarCorreo.Propietario prop = EnviarCorreo.propietarioPorCasa(numeroCasa);
        if (prop == null) {
            mostrarError("La casa " + numeroCasa + " no tiene un correo registrado.\n"
                       + "No se puede registrar el pago sin enviar la confirmación.");
            return;
        }

        // 4. Registrar el pago dentro de una transacción: solo se confirma si el
        //    correo se envía correctamente; si falla, se revierte.
        String sqlInsert = "INSERT INTO Pagos (numero_casa, mes, año, monto) VALUES (?, ?, ?, ?)";
        try (java.sql.Connection con = ConexionDB.getConexion()) {
            con.setAutoCommit(false);
            try (java.sql.PreparedStatement ps = con.prepareStatement(sqlInsert)) {
                ps.setInt(1, numeroCasa);
                ps.setInt(2, numeroMes);
                ps.setInt(3, anio);
                double cuotaActual = Double.parseDouble(jLabel6.getText().replace("Q. ", "").replace(",", ""));
                ps.setDouble(4, cuotaActual);
                ps.executeUpdate();

                String asunto = "Confirmación de pago - Casa " + numeroCasa;
                String cuerpo = "Estimado(a) " + prop.nombre + ",\n\n"
                              + "Se ha registrado exitosamente su pago:\n\n"
                              + "  Casa:   " + numeroCasa + "\n"
                              + "  Mes:    " + mesSel + " " + anio + "\n"
                              + "  Monto:  " + jLabel6.getText() + "\n\n"
                              + "Gracias por estar al día con sus cuotas.\n\n"
                              + "Atentamente,\n" + EmailConfig.NOMBRE_REMITENTE;

                try {
                    EnviarCorreo.enviar(prop.correo, asunto, cuerpo);
                } catch (javax.mail.MessagingException me) {
                    con.rollback();
                    mostrarError("El pago no se registró porque no se pudo enviar el "
                               + "correo de confirmación a " + prop.correo + ":\n"
                               + me.getMessage());
                    return;
                }

                con.commit();
            } catch (java.sql.SQLException e) {
                con.rollback();
                throw e;
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Pago registrado exitosamente.\n\n"
                  + "  Casa:   " + numeroCasa + "\n"
                  + "  Mes:    " + mesSel + " " + anio + "\n"
                  + "  Monto:  " + jLabel6.getText() + "\n\n"
                  + "Se envió la confirmación a " + prop.correo,
                    "Pago exitoso",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();

        } catch (java.sql.SQLException e) {
            mostrarError("Error al registrar pago: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MenuInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean validarSecuenciaMeses(int numeroCasa, int mes, int anio, String[] meses) {
        for (int i = 1; i < mes; i++) {
            String sqlCheck = "SELECT COUNT(*) FROM Pagos WHERE numero_casa = ? AND mes = ? AND año = ?";
            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.PreparedStatement ps = con.prepareStatement(sqlCheck)) {
                ps.setInt(1, numeroCasa);
                ps.setInt(2, i);
                ps.setInt(3, anio);
                java.sql.ResultSet rs = ps.executeQuery();
                if (rs.next() && rs.getInt(1) == 0) {
                    mostrarError("No se puede registrar el pago de " + meses[mes-1] + " " + anio + ".\n"
                               + "El mes de " + meses[i-1] + " " + anio + " está pendiente.");
                    return false;
                }
            } catch (java.sql.SQLException e) {
                mostrarError("Error al validar secuencia: " + e.getMessage());
                return false;
            }
        }
        return true;
    }

    private void limpiarFormulario() {
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
    }

    private void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error de validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RPagos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
