/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.registropropietario;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 * Ventana encargada del registro de propietarios dentro del sistema de
 * administración del condominio.
 *
 * Permite ingresar los datos personales de un propietario (nombre,
 * teléfono y correo electrónico) y asociarlo a una vivienda disponible.
 *
 * Funcionalidades principales:
 * <ul>
 *   <li>Carga automáticamente las casas que no tienen propietario asignado.</li>
 *   <li>Valida que los campos obligatorios estén completos.</li>
 *   <li>Verifica que el teléfono contenga exactamente 8 dígitos.</li>
 *   <li>Valida el formato básico del correo electrónico.</li>
 *   <li>Impide asignar un propietario a una casa ya ocupada.</li>
 *   <li>Registra la información en la base de datos y actualiza la relación
 *       entre propietario y vivienda.</li>
 * </ul>
 *
 * La operación de registro se realiza dentro de una transacción para
 * garantizar la integridad de los datos.
 *
 * @author Gerardo Silvestre
 */
public class RPropietario extends javax.swing.JFrame {

    
    /**
 * Crea la ventana de registro de propietarios.
 *
 * Inicializa los componentes gráficos, configura la ventana,
 * carga las casas disponibles y establece una validación para que
 * el campo de teléfono solo acepte caracteres numéricos.
 */
    public RPropietario() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        cargarCasasDisponibles();

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
            }
        });
    }

    
    /**
 * Carga en el JComboBox todas las casas que no tienen propietario
 * asignado actualmente.
 *
 * Si no existen viviendas disponibles, deshabilita el botón de
 * registro e informa al usuario mediante la lista desplegable.
 */
    private void cargarCasasDisponibles() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Seleccione una casa");
        String sql = "SELECT numero_casa FROM Casas WHERE id_propietario IS NULL ORDER BY numero_casa";
        try (Connection con = ConexionDB.getConexion();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                jComboBox1.addItem(String.valueOf(rs.getInt("numero_casa")));
            }
        } catch (SQLException e) {
            mostrarError("Error al cargar casas: " + e.getMessage());
        }
        if (jComboBox1.getItemCount() == 1) {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Sin casas disponibles");
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }

    
    /**
 * Verifica si un correo electrónico cumple con una validación básica.
 *
 * La validación comprueba que exista un símbolo '@' y que el dominio
 * contenga al menos un punto.
 *
 * @param correo dirección de correo electrónico a validar.
 * @return true si el formato es válido; false en caso contrario.
 */
    private boolean correoEsValido(String correo) {
        int arroba = correo.indexOf('@');
        if (arroba <= 0) return false;
        String dominio = correo.substring(arroba + 1);
        return dominio.contains(".") && !dominio.endsWith(".");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Propietario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre completo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Teléfono:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Correo electrónico:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("No. de casa:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(255, 51, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton2)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    
    /**
 * Registra un nuevo propietario y lo asocia a una vivienda.
 *
 * Realiza las siguientes validaciones:
 * <ul>
 *   <li>Campos obligatorios completos.</li>
 *   <li>Teléfono con 8 dígitos.</li>
 *   <li>Correo electrónico válido.</li>
 *   <li>Existencia de una casa disponible.</li>
 *   <li>Que la vivienda seleccionada no tenga propietario asignado.</li>
 * </ul>
 *
 * Si todas las validaciones son correctas:
 * <ol>
 *   <li>Inserta el propietario en la tabla Propietarios.</li>
 *   <li>Obtiene el ID generado automáticamente.</li>
 *   <li>Asocia el propietario a la vivienda seleccionada.</li>
 *   <li>Confirma la transacción.</li>
 * </ol>
 *
 * @param evt evento generado al presionar el botón Registrar.
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre   = jTextField1.getText().trim();
        String telefono = jTextField2.getText().trim();
        String correo   = jTextField3.getText().trim();
        String casaSel  = (String) jComboBox1.getSelectedItem();
        if (nombre.isEmpty()) { mostrarError("El campo Nombre Completo es obligatorio."); jTextField1.requestFocus(); return; }
        if (telefono.isEmpty()) { mostrarError("El campo Teléfono es obligatorio."); jTextField2.requestFocus(); return; }
        if (!telefono.matches("\\d{8}")) { mostrarError("El teléfono debe tener exactamente 8 dígitos.\nEjemplo: 55551234"); jTextField2.requestFocus(); return; }
        if (correo.isEmpty()) { mostrarError("El campo Correo Electrónico es obligatorio."); jTextField3.requestFocus(); return; }
        if (casaSel == null || casaSel.equals("Sin casas disponibles")) { mostrarError("No hay casas disponibles."); return; }
        if (casaSel.equals("Seleccione una casa")) { mostrarError("Selecciona una casa válida."); return; }
        if (!correoEsValido(correo)) { mostrarError("Correo inválido.\nEjemplo: usuario@dominio.com"); jTextField3.requestFocus(); return; }
        int numeroCasa = Integer.parseInt(casaSel);
        String sqlCheck = "SELECT id_propietario FROM Casas WHERE numero_casa = ?";
        try (Connection con = ConexionDB.getConexion(); PreparedStatement ps = con.prepareStatement(sqlCheck)) {
            ps.setInt(1, numeroCasa);
            ResultSet rs = ps.executeQuery();
            if (rs.next() && rs.getObject("id_propietario") != null) { mostrarError("La casa " + numeroCasa + " ya tiene propietario."); cargarCasasDisponibles(); return; }
        } catch (SQLException e) { mostrarError("Error al verificar: " + e.getMessage()); return; }
        String sqlInsert = "INSERT INTO Propietarios (nombre, telefono, correo) VALUES (?, ?, ?)";
        String sqlUpdate = "UPDATE Casas SET id_propietario = ? WHERE numero_casa = ?";
        try (Connection con = ConexionDB.getConexion()) {
            con.setAutoCommit(false);
            int idNuevo;
            try (PreparedStatement ps = con.prepareStatement(sqlInsert, Statement.RETURN_GENERATED_KEYS)) {
                ps.setString(1, nombre); ps.setString(2, telefono); ps.setString(3, correo);
                ps.executeUpdate();
                ResultSet keys = ps.getGeneratedKeys(); keys.next(); idNuevo = keys.getInt(1);
            }
            try (PreparedStatement ps = con.prepareStatement(sqlUpdate)) {
                ps.setInt(1, idNuevo); ps.setInt(2, numeroCasa); ps.executeUpdate();
            }
            con.commit();
            JOptionPane.showMessageDialog(this, "Propietario registrado exitosamente.\n\n  Nombre: " + nombre + "\n  Casa: " + numeroCasa + "\n  Telefono: " + telefono + "\n  Correo: " + correo, "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario(); cargarCasasDisponibles();
        } catch (SQLException e) { mostrarError("Error al registrar: " + e.getMessage()); }

    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
 * Limpia todos los campos del formulario y restablece la selección
 * inicial de la lista de viviendas.
 *
 * @param evt evento generado al presionar el botón Limpiar.
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       limpiarFormulario();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
 * Regresa al menú principal del sistema y cierra la ventana actual.
 *
 * @param evt evento generado al presionar el botón Volver.
 */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          new MenuInicio().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
 * Restablece todos los campos del formulario a sus valores iniciales.
 *
 * También posiciona el cursor nuevamente en el campo de nombre para
 * facilitar un nuevo registro.
 */
   private void limpiarFormulario() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        if (jComboBox1.getItemCount() > 0) {
            jComboBox1.setSelectedIndex(0);
        }
        jTextField1.requestFocus();
    }

   
   /**
 * Muestra un mensaje de advertencia al usuario.
 *
 * @param mensaje descripción del error o validación incumplida.
 */
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error de validación",
                JOptionPane.WARNING_MESSAGE);
    }
    
    
    /**
 * Punto de entrada para ejecutar de forma independiente la ventana
 * de registro de propietarios.
 *
 * Configura el tema visual FlatDarcula y muestra la interfaz gráfica.
 *
 * @param args argumentos de línea de comandos.
 */
    public static void main(String args[]) {
        try {
            com.formdev.flatlaf.FlatDarculaLaf.setup();
        } catch (Exception e) {
            // ignorar
        }
        java.awt.EventQueue.invokeLater(() -> new RPropietario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
